name: Deploy Development ENV

on:
  push:
    branches: [dev]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/cd.yml
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    with:
      env_tag: dev
      environment: Development
      AWS_ECR_REPOSITORY: devplus-system-fe

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-1

  deploy:
    uses: ./.github/workflows/ci.yml
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    with:
      env_tag: dev
      environment: Development
      deploy_dir: devplus-system-fe
      AWS_ECR_REPOSITORY: devplus-system-fe

    secrets:
      AWS_EC2_HOST_NAME: ${{ secrets.AWS_EC2_HOST_NAME }}
      AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME }}
      AWS_EC2_ACCESS_KEY: ${{ secrets.AWS_EC2_ACCESS_KEY }}
      AWS_REGION: ap-southeast-1
